Feature/1.6/fix http services listed as discoverable
casualcore/casual pull request #151
Opened 2023-02-20 06:50 UTC by AlbsAgren

2023-02-20 20:25 UTC, OlofGullnas commented
Noticed that the change of color for #branches seems to be to white. At least judging from naming. I have not checked effect of the escape sequence "\033[0;37m".
Selecting colors can be difficult. What is visible can be difficult to predict. The color setup of the users terminal is not known. Quite common choices are black or white background. White on white is not very visible, nor black on black.

2023-02-21 14:15 UTC, AlbsAgren commented
Fair point, a higher contrast color might be a better choice. Before this it was black rather than the grey indicated by the constant, which obivously wasnt easy to read on a terminal with a blackground.

2023-02-21 15:59 UTC, OlofGullnas commented
I have used putty for many years. It has:

- default  and bold foreground 
- default and bold background
- and a bunch of ANSI colors (also with bold variants). Black and white exist. 

In Putty the RGB settings for all the colors can be changed in settings...

A similar set of colors seems to be common.

I have for many years used some conventions for my terminals: 
- Development systems have either very dark background (almost black, rgb 15, 15, 15 or so) with very light grey default foreground (rgb 240, 240, 240), Or they have the exact opposite Dark text on light background.
- Production system generally have a "pinkish" (low saturation) background  with dark tesxt (red is a "danger" signal)
- System test (if different from development) and similar have light yellow (low saturation) background with dark foreground (yellow is a "warning" signal)

The idea is to make it obvious when the terminal is connected to a production (or critical in some sense) system. I want to avoid doing bad things by mistake. :-) 

I would avoid using "white" or "black" as colors for text as they can be hard to read with white or black backgrounds. The "deafult" color for text should probably be "default foreground" (is there a standardized escape sequence to select this? It is probably "<esc> [0m") and never black or white. This is based on the assumption that the users terminal is configured so that default foreground is readable against configured default background.  I also think that "blue" often is hard to read, Especially with a black/dark background , The other colors are better. Yellow can be a little difficult with my yellowish background but usually works with dark and light background.

Can  also consider using "reverse" ("<esc>[7m") in combinaton with colors if more variants are needed! This reverses the role of foreground anf background colors. This should work well with colors that stand out well against both black and white,

2023-02-22 10:31 UTC, lazan requested changes
I think the `string::compose` is "better".

2023-02-22 10:31 UTC, lazan commented on middleware/administration/unittest/source/cli/test_transaction.cpp
> +      TEST( cli_transaction, list_transactions)
Nice!

2023-02-22 10:31 UTC, lazan commented on middleware/transaction/source/manager/admin/cli.cpp
> +                        };
You could use 
```cpp
auto format_owner = []( auto& value) -> std::string  
{
   if( value.owner.pid)
     return string::compose( value.owner.pid);
   else
     return "-":      
}
```

2023-02-23 07:33 UTC, AlbsAgren commented on middleware/transaction/source/manager/admin/cli.cpp
> +                        };
Fixed

2023-02-23 11:36 UTC, lazan approved these changes

2023-02-23 11:36 UTC, merged