discovery - handle prospect services (#198)
casualcore/casual pull request #206
Opened 2023-05-26 12:34 UTC by ahhud

Before:
In-flight discovery request was not considered upon rediscovery requests and explore resulting in missing services ( and queues) routing to new connections.

After:
Every in-flight discovery request registers it's resources to a prospect list which is considered when doing rediscover and exlpore. After the discovery request is done all prospect claims are removed from the prospect list made by that correlation.

2023-05-26 14:10 UTC, lazan requested changes
A general note: Are you not worried about logging state in a few places? Since we got the option of dumping the state by `internal --state-dump <pid>`. Maybe _discovery_ does not generally contain that much state?  It gets "harder" to read the loggs in my opinion, on the other hand, all state is logged which could be very helpful :) I dunno...

2023-05-26 14:10 UTC, lazan commented on middleware/domain/source/discovery/state.cpp
> +         algorithm::container::erase_if( services, []( auto pair) { return pair.second.empty();});
You could erase the correlation in the same algorithm, hence only do one pass.

```suggestion
         algorithm::container::erase_if( services, [ &correlation]( auto& pair) 
         {
             return algorithm::container::erase( pair.second, correlation).empty();
         );
```
And you need to take the pair by reference.

2023-05-26 14:10 UTC, lazan commented on middleware/domain/source/discovery/state.cpp
> +         algorithm::transform( queues, content.queues, []( auto pair) { return pair.first;});
Take `pair` by reference.

2023-05-26 14:17 UTC, ahhud commented
> A general note: Are you not worried about logging state in a few places? Since we got the option of dumping the state by `internal --state-dump <pid>`. Maybe _discovery_ does not generally contain that much state? It gets "harder" to read the loggs in my opinion, on the other hand, all state is logged which could be very helpful :) I dunno...

It was a very small state. But you are correct, I will remove it.

2023-05-26 14:45 UTC, ahhud commented on middleware/domain/source/discovery/state.cpp
> +         algorithm::container::erase_if( services, []( auto pair) { return pair.second.empty();});
@lazan So it is safe to remove elements from _services_ when inside a range for-loop over _services_?

2023-05-26 14:48 UTC, ahhud commented on middleware/domain/source/discovery/state.cpp
> +         algorithm::container::erase_if( services, []( auto pair) { return pair.second.empty();});
Now I got it.

2023-05-26 15:17 UTC, ahhud commented
@lazan I made the proposed changes and force-pushed

2023-05-28 17:23 UTC, lazan approved these changes

2023-05-28 17:34 UTC, merged