http: outbound always send metric on service call
casualcore/casual pull request #407
Opened 2024-08-27 07:29 UTC by AlbsAgren

This commit ensures that the outbound always sends metrics to the service manager even when a call fails immediately due to violated preconditions.

Resolves #397

2024-08-27 08:39 UTC, lazan requested changes

2024-08-27 08:39 UTC, lazan commented on middleware/http/include/http/outbound/state.h
> +
`State` should never "do anything", other than mutate it's own state. 
This to reduce complexity. Other stuff actually do stuff and mutate state to reflect what's done.
Also, with this "rule" we don't need ask our self, where "to do this stuff" -> less confusion and more coherent code.
Move this to _handle_.

There might be stuff that is "done" in a few places in other `State` -> if so, it should be removed.

2024-08-27 10:38 UTC, lazan approved these changes
Looking good.

2024-08-27 10:38 UTC, lazan commented on middleware/http/include/http/outbound/state.h
> +#include "common/communication/instance.h"
Remove

2024-08-29 06:02 UTC, ahhud approved these changes

2024-08-29 08:43 UTC, merged