Feature/1.5/patch.12 service use ipc multiplex send everywhere we send
casualcore/casual pull request #48
Opened 2022-05-15 18:57 UTC by AlbsAgren

2022-05-15 21:08 UTC, lazan requested changes
We need to do something about if "targets" are unavailable later during multiplex send. Two options:
* Use "flush::send" in these cases, not attractive...
* Add a `common::unique_function` callable to the multiplex send state, and if "target" is unavailable AND  _callable_ is not 'null', call it (to send error message and such..

2022-05-15 21:08 UTC, lazan commented on middleware/service/source/forward/handle.cpp
> +                        if( ! state.multiplex.send( message.process.ipc, request))
What if the caller "is gone" later? Hmm, we would not send an error reply...

2022-05-15 21:08 UTC, lazan commented on middleware/service/source/forward/main.cpp
> +                  };
Nice! We may want to consume _next message_ until device is depleted, or we've reached some _platform::batch::..limit_ (low, under 20 maybe). Not that important in the forward I'm guessing. Not that much load...

2022-05-15 21:08 UTC, lazan commented on middleware/service/source/manager/handle.cpp
> +                  auto reply( State& state, const state::instance::Caller& caller, common::code::xatmi code)
A given extension to the "api", nice.

2022-05-15 21:08 UTC, lazan commented on middleware/service/source/manager/handle.cpp
> +                              if( ! local::optional::send( state, message.process.ipc, reply))
What if the caller "is gone" later? Hmm, we would not discard the reservation.

2022-05-15 21:08 UTC, lazan commented on middleware/service/include/service/forward/state.h
> +         State()
```cpp
inline State() ...
```

2022-05-15 21:08 UTC, lazan commented on middleware/service/source/manager/handle.cpp
> -               } // eventually
The best change! Removal of code...

2022-05-15 21:20 UTC, lazan commented
Also: The commit header messages should only refer to `service -  ...`
* `service - use multiplex send in manager`.   
* `service - use multiplex send in forward`.
Or something similar. The first _word_ is the _module_, and we don't use finer granularity, if we don't need to. 
You could squash these two also.

2022-05-27 12:15 UTC, lazan commented
Somethings must have gone wrong with the "rebase from feature/1.5/patch.12". You might need to move this to another branch, take out a new branch from origin/feature/1.5/patch.12  and cherry-pick your commits.

2022-05-27 13:37 UTC, AlbsAgren commented
What doesn't look right? I've squashed my commits together and rebased off of feature/1.5/patch.12 (though I see now that there's been another pr merged since I rebased). Other than that, the diff looks correct to me as far as I can tell.

2022-05-27 15:53 UTC, lazan commented
My bad! You're totally right, sorry.

2022-05-27 16:21 UTC, lazan requested changes

2022-05-27 16:21 UTC, lazan commented on middleware/service/source/forward/handle.cpp
> +                        state.multiplex.send( message.process.ipc, request, [ &state, &request, service_name = message.service.name]( auto& destination, auto& complete)
The request that you capture by ref, won't be alive when the lambda is invoked. Pretty much all things beside `State` must be capture by value.

2022-05-27 16:21 UTC, lazan commented on middleware/service/source/manager/handle.cpp
> +                              state.multiplex.send( message.process.ipc, reply, [ &state, &handle]( auto& destination, auto& complete){
`handle` captured by ref. capture pid by value.

2022-05-27 16:57 UTC, AlbsAgren commented on middleware/service/source/forward/handle.cpp
> +                        state.multiplex.send( message.process.ipc, request, [ &state, &request, service_name = message.service.name]( auto& destination, auto& complete)
Of course, too much javascript on the brain.

2022-05-27 20:22 UTC, lazan commented on middleware/service/source/forward/handle.cpp
> +                        state.multiplex.send( message.process.ipc, request, [ &state, &request, service_name = message.service.name]( auto& destination, auto& complete)
:)

2022-05-29 11:12 UTC, lazan approved these changes
Seams ok. Good work. If you merge it your self (I think you can) use _rebase merge_ and be aware that GitHub change the sha-sum in your commits, so your local branch won't be "equal".

2022-05-31 14:01 UTC, closed without merging