File mechanism wants to be merged to main
casualcore/casual pull request #489
Opened 2024-12-22 16:01 UTC by KristianIvarsson

The basic functionality is ready and done

Probably some CLI features will be added later on

2025-01-08 14:35 UTC, lazan requested changes
First pass :)

2025-01-08 14:35 UTC, lazan commented on middleware/file/documentation/file.development.md
> +
Shouldn't we include tx_begin(), tx_commit() in these examples? Just to make it clear to the reader that transaction is the major part of the whole file-manager...

2025-01-08 14:35 UTC, lazan commented on middleware/file/include/file/api/c/file.h
> +#ifdef __cplusplus
Pretty good. I think this is more than good enough. 
I would argue that a _flag_ to `casual_file_reserve` would be a more _posix style_ api. And, more importantly, opens up future non intrusive features.
But I'm fine as is.

2025-01-08 14:35 UTC, lazan commented on middleware/file/include/file/code.h
Nice

2025-01-08 14:35 UTC, lazan commented on middleware/file/include/file/factory.h
> +            inline auto request( std::filesystem::path path)
Why are these inline? Any particular reason?

2025-01-08 14:35 UTC, lazan commented on middleware/file/include/file/manager/admin/model.h
> +         };
Simple and clean.

2025-01-08 14:35 UTC, lazan commented on middleware/file/include/file/manager/handle.h
> +      dispatch_type create( State& state);
_file-manager_

2025-01-08 14:35 UTC, lazan commented on middleware/file/source/api/c/file.cpp
> +      extern "C"
I don't think you need `extern C` in the TU

2025-01-08 14:35 UTC, lazan commented on middleware/file/source/manager/resource.cpp
I strongly prefer not to send anything from _resouce.cpp_. If possible all send should be in _handle.cpp_ . It's more symmetric.  receive-request -> send-reply at in the same function. 
This would mean that you return the message that _handle_ should send back to caller. Then it's easy to unittest the resource as a bonus.

2025-01-08 14:35 UTC, lazan commented on middleware/file/source/manager/handle.cpp
> +                        resource::commit( state, message);
I would like `resource::commit(..)` to return the message and this function sends the reply to caller. Much clearer that the reply is sent.

2025-01-08 15:33 UTC, KristianIvarsson commented on middleware/file/documentation/file.development.md
> +
Good idea, we'll put that into some commit sometime

2025-01-08 15:34 UTC, KristianIvarsson commented on middleware/file/include/file/api/c/file.h
> +#ifdef __cplusplus
The documentation (description) is wrong though

2025-01-08 15:37 UTC, KristianIvarsson commented on middleware/file/include/file/factory.h
> +            inline auto request( std::filesystem::path path)
Hmm, it must be some leftovers to avoid ODR in some earlier design and I guess it can be removed now

2025-01-08 15:45 UTC, KristianIvarsson commented on middleware/file/source/manager/resource.cpp
Maybe agreed, but replies are not always gonna be sent but instead sent in other scenarios, such as when a _commit_ is issued, maybe replies for _reserve_ is gonna be sent (as well)

Maybe I don't understand what you're aiming for ?

2025-01-18 10:30 UTC, lazan commented on middleware/file/include/file/factory.h
This is a _message factory_? 
* should not the file name reflect that?
* why header only?

In the rest of `causal` I think _factory_ is used for dynamic dispatch factories (sort of classic factory). We have very few. 
This is more of a _create helper_? 
`file/message/create.h` ?

2025-01-18 10:30 UTC, lazan commented on middleware/file/source/manager/handle.cpp
> +                     };
Have ha `resource::prepare` for symmetry.

2025-01-18 11:29 UTC, KristianIvarsson commented on middleware/file/include/file/factory.h
Give a name suggestion

It is used from 2 binaries and thus we need to build it as a object file or an archve and link it into those two binaries so this was just simpler to have it as header only

2025-01-18 11:43 UTC, lazan commented on middleware/file/include/file/factory.h
I just gave a name suggestion ..?
Yeah, either an archive or you just keep the object-file(s) in a python-list and add them in the binaries that needs them.

2025-01-18 11:44 UTC, KristianIvarsson commented on middleware/file/source/manager/handle.cpp
> +                     };
Greate point (fixed now)

2025-01-18 11:45 UTC, lazan commented on middleware/file/include/file/factory.h
`file::create::[non::]blocking::request( ...)`

2025-01-18 11:52 UTC, KristianIvarsson commented on middleware/file/include/file/factory.h
Did some more proper renaming of namespaces (and removed a forgotten ìnline` directive, but didn't change any file structure)

2025-01-19 17:21 UTC, lazan approved these changes
Nice.

2025-01-19 17:23 UTC, merged