service - fix metrics to use route name
casualcore/casual pull request #78
Opened 2022-09-26 11:04 UTC by AlbsAgren

2022-09-26 11:14 UTC, lazan requested changes
Looking good, and easy to understan. The unittest was very concise and easy to understand.

A few pointers to fix though.

2022-09-26 11:14 UTC, lazan commented on middleware/gateway/source/group/inbound/state.cpp
> +                  }
You could do some exchange or swap instead of copies, right?

2022-09-26 11:14 UTC, lazan commented on test/unittest/source/test_service.cpp
> +         auto len = tptypes( buffer, nullptr, nullptr);
A scope around the variables (and usage of the variables). Mitigates unwanted usage and a good practice in general to keep scopes as small as possible.

2022-09-26 12:46 UTC, lazan approved these changes, later dismissed
Nice!

2022-09-28 13:21 UTC, ahhud approved these changes

2022-09-28 17:09 UTC, merged